# Generated by Django 3.2.3 on 2021-08-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='desc',
            field=models.TextField(help_text='简要描述', verbose_name='简要描述'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='id',
            field=models.AutoField(help_text='Id主键', primary_key=True, serialize=False, verbose_name='Id主键'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=50, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='tester',
            field=models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员'),
        ),
    ]
