# Generated by Django 3.2.3 on 2021-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='计划名称', max_length=200, verbose_name='计划名称')),
                ('structure_time', models.CharField(help_text='构建时间', max_length=100, verbose_name='构建时间')),
                ('env_id', models.IntegerField(help_text='环境id', verbose_name='环境id')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'tb_testplans',
            },
        ),
    ]
